### ISSUE TITLE
Helm repo error

### ISSUE THREAD

**Issue by IDerr** [tongdun/td-redis-operator#10]
Hello
when adding a repo to my helmm I have this issue, perhaps it needs a name for the version 0.1.0 for the operator

Thanks a lot 
index.go:346: skipping loading invalid entry for chart "td-redis-operator" "0.1.0" from https://tongdun.github.io/td-redis-operator/charts/td-redis-operator: validation: chart.metadata.name is required

**Comment by DoubleJ213** [comment]
It works well for me. can you provide more information such as helm version and install steps and so on

**Comment by IDerr** [comment]
Oh it's not during the install, it's during the helm repo update
It may be linked to the https://github.com/tongdun/td-redis-operator/blob/main/charts/td-redis-operator/index.yaml
I think it needs a name field

**Comment by IDerr** [comment]
for example
```
apiVersion: v1
entries:
  alpine:
    - created: 2016-10-06T16:23:20.499814565-06:00
      description: Deploy a basic Alpine Linux pod
      digest: 99c76e403d752c84ead610644d4b1c2f2b453a74b921f422b9dcb8a7c8b559cd
      home: https://helm.sh/helm
      name: alpine
      sources:
      - https://github.com/helm/helm
      urls:
      - https://technosophos.github.io/tscharts/alpine-0.2.0.tgz
      version: 0.2.0
    - created: 2016-10-06T16:23:20.499543808-06:00
      description: Deploy a basic Alpine Linux pod
      digest: 515c58e5f79d8b2913a10cb400ebb6fa9c77fe813287afbacf1a0b897cd78727
      home: https://helm.sh/helm
      name: alpine
      sources:
      - https://github.com/helm/helm
      urls:
      - https://technosophos.github.io/tscharts/alpine-0.1.0.tgz
      version: 0.1.0
  nginx:
    - created: 2016-10-06T16:23:20.499543808-06:00
      description: Create a basic nginx HTTP server
      digest: aaff4545f79d8b2913a10cb400ebb6fa9c77fe813287afbacf1a0b897cdffffff
      home: https://helm.sh/helm
      name: nginx
      sources:
      - https://github.com/helm/charts
      urls:
      - https://technosophos.github.io/tscharts/nginx-1.1.0.tgz
      version: 1.1.0
generated: 2016-10-06T16:23:20.499029981-06:00

```
