### ISSUE TITLE
Service account being created twice

### ISSUE THREAD

**Issue by stevefan1999-personal** [tongdun/td-redis-operator#23]
```
---
# Source: td-redis-operator/templates/operator-rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: td-redis-operator
  namespace: kube-system
---
# Source: td-redis-operator/templates/operator.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: td-redis-operator
  namespace: kube-system
```
